# Generated by Django 4.0.5 on 2023-09-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_visualizarcatalogopermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='condicion_precio',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=10),
        ),
    ]
